const countriesList = [
  { code: 'ALL_COMBINED', name: 'All Countries (Combined)' },
  { code: "1000", name: "United States of America" },
  { code: "1010", name: "Greenland" },
  { code: "1220", name: "Canada" },
  { code: "1610", name: "Saint Pierre and Miquelon" },
  { code: "2010", name: "Mexico" },
  { code: "2050", name: "Guatemala" },
  { code: "2080", name: "Belize" },
  { code: "2110", name: "El Salvador" },
  { code: "2150", name: "Honduras" },
  { code: "2190", name: "Nicaragua" },
  { code: "2230", name: "Costa Rica" },
  { code: "2250", name: "Panama" },
  { code: "2320", name: "Bermuda" },
  { code: "2360", name: "Bahamas" },
  { code: "2390", name: "Cuba" },
  { code: "2410", name: "Jamaica" },
  { code: "2430", name: "Turks and Caicos Islands" },
  { code: "2440", name: "Cayman Islands" },
  { code: "2450", name: "Haiti" },
  { code: "2470", name: "Dominican Republic" },
  { code: "2481", name: "Anguilla" },
  { code: "2482", name: "British Virgin Islands" },
  { code: "2483", name: "Saint Kitts and Nevis" },
  { code: "2484", name: "Antigua and Barbuda" },
  { code: "2485", name: "Montserrat" },
  { code: "2486", name: "Dominica" },
  { code: "2487", name: "Saint Lucia" },
  { code: "2488", name: "Saint Vincent and the Grenadines" },
  { code: "2489", name: "Grenada" },
  { code: "2720", name: "Barbados" },
  { code: "2740", name: "Trinidad and Tobago" },
  { code: "2774", name: "Sint Maarten" },
  { code: "2777", name: "Curacao" },
  { code: "2779", name: "Aruba" },
  { code: "2831", name: "Guadeloupe" },
  { code: "2839", name: "Martinique" },
  { code: "3010", name: "Colombia" },
  { code: "3070", name: "Venezuela" },
  { code: "3120", name: "Guyana" },
  { code: "3150", name: "Suriname" },
  { code: "3170", name: "French Guiana" },
  { code: "3310", name: "Ecuador" },
  { code: "3330", name: "Peru" },
  { code: "3350", name: "Bolivia" },
  { code: "3370", name: "Chile" },
  { code: "3510", name: "Brazil" },
  { code: "3530", name: "Paraguay" },
  { code: "3550", name: "Uruguay" },
  { code: "3570", name: "Argentina" },
  { code: "3720", name: "Falkland Islands (Islas Malvinas)" },
  { code: "4000", name: "Iceland" },
  { code: "4010", name: "Sweden" },
  { code: "4031", name: "Svalbard and Jan Mayen" },
  { code: "4039", name: "Norway" },
  { code: "4050", name: "Finland" },
  { code: "4091", name: "Faroe Islands" },
  { code: "4099", name: "Denmark, except Greenland" },
  { code: "4120", name: "United Kingdom" },
  { code: "4190", name: "Ireland" },
  { code: "4210", name: "Netherlands" },
  { code: "4231", name: "Belgium" },
  { code: "4239", name: "Luxembourg" },
  { code: "4271", name: "Andorra" },
  { code: "4272", name: "Monaco" },
  { code: "4279", name: "France" },
  { code: "4280", name: "Germany (Federal Republic of Germany)" },
  { code: "4330", name: "Austria" },
  { code: "4351", name: "Czech Republic" },
  { code: "4359", name: "Slovakia" },
  { code: "4370", name: "Hungary" },
  { code: "4411", name: "Liechtenstein" },
  { code: "4419", name: "Switzerland" },
  { code: "4470", name: "Estonia" },
  { code: "4490", name: "Latvia" },
  { code: "4510", name: "Lithuania" },
  { code: "4550", name: "Poland" },
  { code: "4621", name: "Russia" },
  { code: "4622", name: "Belarus" },
  { code: "4623", name: "Ukraine" },
  { code: "4631", name: "Armenia" },
  { code: "4632", name: "Azerbaijan" },
  { code: "4633", name: "Georgia" },
  { code: "4634", name: "Kazakhstan" },
  { code: "4635", name: "Kyrgyzstan" },
  { code: "4641", name: "Moldova (Republic of Moldova)" },
  { code: "4642", name: "Tajikistan" },
  { code: "4643", name: "Turkmenistan" },
  { code: "4644", name: "Uzbekistan" },
  { code: "4700", name: "Spain" },
  { code: "4710", name: "Portugal" },
  { code: "4720", name: "Gibraltar" },
  { code: "4730", name: "Malta" },
  { code: "4751", name: "San Marino" },
  { code: "4752", name: "Holy See (Vatican City)" },
  { code: "4759", name: "Italy" },
  { code: "4791", name: "Croatia" },
  { code: "4792", name: "Slovenia" },
  { code: "4793", name: "Bosnia and Herzegovina" },
  { code: "4794", name: "North Macedonia" },
  { code: "4801", name: "Serbia" },
  { code: "4803", name: "Kosovo" },
  { code: "4804", name: "Montenegro" },
  { code: "4810", name: "Albania" },
  { code: "4840", name: "Greece" },
  { code: "4850", name: "Romania" },
  { code: "4870", name: "Bulgaria" },
  { code: "4890", name: "Turkey" },
  { code: "4910", name: "Cyprus" },
  { code: "5020", name: "Syria (Syrian Arab Republic)" },
  { code: "5040", name: "Lebanon" },
  { code: "5050", name: "Iraq" },
  { code: "5070", name: "Iran" },
  { code: "5081", name: "Israel" },
  { code: "5082", name: "Gaza Strip administered by Israel" },
  { code: "5083", name: "West Bank administered by Israel" },
  { code: "5110", name: "Jordan" },
  { code: "5130", name: "Kuwait" },
  { code: "5170", name: "Saudi Arabia" },
  { code: "5180", name: "Qatar" },
  { code: "5200", name: "United Arab Emirates" },
  { code: "5210", name: "Yemen (Republic of Yemen)" },
  { code: "5230", name: "Oman" },
  { code: "5250", name: "Bahrain" },
  { code: "5310", name: "Afghanistan" },
  { code: "5330", name: "India" },
  { code: "5350", name: "Pakistan" },
  { code: "5360", name: "Nepal" },
  { code: "5380", name: "Bangladesh" },
  { code: "5420", name: "Sri Lanka" },
  { code: "5460", name: "Burma (Myanmar)" },
  { code: "5490", name: "Thailand" },
  { code: "5520", name: "Vietnam" },
  { code: "5530", name: "Laos (Lao People's Democratic Republic)" },
  { code: "5550", name: "Cambodia" },
  { code: "5570", name: "Malaysia" },
  { code: "5590", name: "Singapore" },
  { code: "5600", name: "Indonesia" },
  { code: "5601", name: "Timor-Leste" },
  { code: "5610", name: "Brunei" },
  { code: "5650", name: "Philippines" },
  { code: "5660", name: "Macao" },
  { code: "5682", name: "Bhutan" },
  { code: "5683", name: "Maldives" },
  { code: "5700", name: "China" },
  { code: "5740", name: "Mongolia" },
  { code: "5790", name: "North Korea (Democratic People's Republic of Korea)" },
  { code: "5800", name: "South Korea (Republic of Korea)" },
  { code: "5820", name: "Hong Kong" },
  { code: "5830", name: "Taiwan" },
  { code: "5880", name: "Japan" },
  { code: "6021", name: "Australia" },
  { code: "6022", name: "Norfolk Island" },
  { code: "6023", name: "Cocos (Keeling) Islands" },
  { code: "6024", name: "Christmas Island (in the Indian Ocean)" },
  { code: "6029", name: "Heard Island and McDonald Islands" },
  { code: "6040", name: "Papua New Guinea" },
  { code: "6141", name: "New Zealand" },
  { code: "6142", name: "Cook Islands" },
  { code: "6143", name: "Tokelau" },
  { code: "6144", name: "Niue" },
  { code: "6150", name: "Samoa (Western Samoa)" },
  { code: "6223", name: "Solomon Islands" },
  { code: "6224", name: "Vanuatu" },
  { code: "6225", name: "Pitcairn Islands" },
  { code: "6226", name: "Kiribati" },
  { code: "6227", name: "Tuvalu" },
  { code: "6412", name: "New Caledonia" },
  { code: "6413", name: "Wallis and Futuna" },
  { code: "6414", name: "French Polynesia" },
  { code: "6810", name: "Marshall Islands" },
  { code: "6820", name: "Micronesia, Federated States of" },
  { code: "6830", name: "Palau" },
  { code: "6862", name: "Nauru" },
  { code: "6863", name: "Fiji" },
  { code: "6864", name: "Tonga" },
  { code: "7140", name: "Morocco" },
  { code: "7210", name: "Algeria" },
  { code: "7230", name: "Tunisia" },
  { code: "7250", name: "Libya" },
  { code: "7290", name: "Egypt" },
  { code: "7321", name: "Sudan" },
  { code: "7323", name: "South Sudan" },
  { code: "7380", name: "Equatorial Guinea" },
  { code: "7410", name: "Mauritania" },
  { code: "7420", name: "Cameroon" },
  { code: "7440", name: "Senegal" },
  { code: "7450", name: "Mali" },
  { code: "7460", name: "Guinea" },
  { code: "7470", name: "Sierra Leone" },
  { code: "7480", name: "Cote d'Ivoire" },
  { code: "7490", name: "Ghana" },
  { code: "7500", name: "Gambia" },
  { code: "7510", name: "Niger" },
  { code: "7520", name: "Togo" },
  { code: "7530", name: "Nigeria" },
  { code: "7540", name: "Central African Republic" },
  { code: "7550", name: "Gabon" },
  { code: "7560", name: "Chad" },
  { code: "7580", name: "Saint Helena" },
  { code: "7600", name: "Burkina Faso" },
  { code: "7610", name: "Benin" },
  { code: "7620", name: "Angola" },
  { code: "7630", name: "Congo, Republic of the Congo" },
  { code: "7642", name: "Guinea-Bissau" },
  { code: "7643", name: "Cabo Verde" },
  { code: "7644", name: "Sao Tome and Principe" },
  { code: "7650", name: "Liberia" },
  { code: "7660", name: "Congo, Democratic Republic of the Congo (formerly Zaire)" },
  { code: "7670", name: "Burundi" },
  { code: "7690", name: "Rwanda" },
  { code: "7700", name: "Somalia" },
  { code: "7741", name: "Eritrea" },
  { code: "7749", name: "Ethiopia" },
  { code: "7770", name: "Djibouti" },
  { code: "7780", name: "Uganda" },
  { code: "7790", name: "Kenya" },
  { code: "7800", name: "Seychelles" },
  { code: "7810", name: "British Indian Ocean Territory" },
  { code: "7830", name: "Tanzania (United Republic of Tanzania)" },
  { code: "7850", name: "Mauritius" },
  { code: "7870", name: "Mozambique" },
  { code: "7880", name: "Madagascar" },
  { code: "7881", name: "Mayotte" },
  { code: "7890", name: "Comoros" },
  { code: "7904", name: "Reunion" },
  { code: "7905", name: "French Southern and Antarctic Lands" },
  { code: "7910", name: "South Africa" },
  { code: "7920", name: "Namibia" },
  { code: "7930", name: "Botswana" },
  { code: "7940", name: "Zambia" },
  { code: "7950", name: "Eswatini" },
  { code: "7960", name: "Zimbabwe" },
  { code: "7970", name: "Malawi" },
  { code: "7990", name: "Lesotho" },
  { code: "9030", name: "Puerto Rico" },
  { code: "9110", name: "Virgin Islands of the United States" },
  { code: "9350", name: "Guam" },
  { code: "9510", name: "American Samoa" },
  { code: "9610", name: "Northern Mariana Islands" },
  { code: "9800", name: "United States Minor Outlying Islands" }
];

module.exports = (req, res) => {
  const apiKey = req.headers['x-api-key'];
  const validKeys = process.env.API_KEYS?.split(',') || ['test-key-123'];
  
  if (!apiKey || !validKeys.includes(apiKey)) {
    return res.status(401).json({ error: 'Invalid or missing API key' });
  }
  
  res.status(200).json({
    countries: countriesList,
    total: countriesList.length
  });
};